### ISSUE TITLE
Problem with TCA. Pages can not be selected for tx_bgmhreflang_2

### ISSUE THREAD

**Issue by niederberger-qw** [bgmgmbh/extension-bgm_hreflang#21]
![grafik](https://user-images.githubusercontent.com/85213755/167372573-46bcf5f2-fdd5-433f-b6cb-4231fec97d42.png)

This is in the TCA:

'fieldControl' => [
                'elementBrowser' => [
                    'disabled' => true,
                ],
            ],

Why is that the case?

**Comment by mhuber84** [comment]
Hi @niederberger-qw,

the only reason why tx_bgmhreflang_2 exists is, that you can delete a relation between to pages, even if it is the opposite side of the connection ("MM_opposite_field"). New relations should always be added in tx_bgmhreflang_1. 

To be honest the "Find records" search field is wrong here, too. Perhaps the option "hideSuggest" didn't exist when I first implemented the extension. I will remove it with the next release. :-) 
I think there is no way to remove the sorting buttons.

**Comment by niederberger-qw** [comment]
@mhuber84 thank you very much. I see.
