### ISSUE TITLE
TYPO3 11 compatibility

### ISSUE THREAD

**Issue by jp1987** [bgmgmbh/extension-bgm_hreflang#24]
I'd like to use this extension in TYPO3 11 and am available to help with the work, is there a list of known issues/challenges that need solving?

**Comment by mhuber84** [comment]
Hi @jp1987,

thank you for your offer to help me on a release for TYPO3 11. I was already working on this issue (and some caching issues). But for 11 there where not many changes needed :-).

You could help me by testing [branch 4-0-5](https://github.com/bgmgmbh/extension-bgm_hreflang/tree/4-0-5). It should work with TYPO3 11.

Greetings,
Marco

**Comment by jp1987** [comment]
Awesome, will have a look in the next few weeks :)

**Comment by mhuber84** [comment]
Today I released version 4.0.5 which is compatible with TYPO3 11: https://extensions.typo3.org/extension/bgm_hreflang

**Comment by jp1987** [comment]
Amazing, thank you!!
