### ISSUE TITLE
[QUESTION] packagist support?

### ISSUE THREAD

**Issue by glucka** [bgmgmbh/extension-bgm_hreflang#5]
Hi, any plan for https://packagist.org release? For a clean composer mode. ;)

**Comment by mhuber84** [comment]
I'll try. I hope I find some time this weekend...

**Comment by mgrundkoetter** [comment]
all extensions in TER are automatically published as composer packages as well: https://composer.typo3.org/satis.html#typo3-ter/bgm-hreflang

**Comment by mhuber84** [comment]
Finally: https://packagist.org/packages/bgm/bgm-hreflang ;-)
